services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: websocket_app
        restart: unless-stopped
        ports:
            -   "8080:8080"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: websocket_postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        ports:
            - "5435:5432"  # Aniq port xaritasi qo'shildi

    pgadmin:
        image: dpage/pgadmin4
        container_name: websocket_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "9093:80"  # Port xaritasi tuzatildi
        networks:
            - app-network

    nginx:
        container_name: websocket_nginx
        image: nginx:alpine
        ports:
            - "8021:80"  # 8008 porti o'rniga 8010 foydalanilyapti
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    node:
        image: node:22
        container_name: websocket_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run dev"
        networks:
            - app-network


volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
